name: flutter_testing
description: How to test in flutter

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1


flutter:

  uses-material-design: true